env:
  browser: true
  es6: true
  jest: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  module: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
